import { Body, Controller, Get, Header, HttpCode, HttpStatus, Param, ParseUUIDPipe, Patch, Post, Query } from '@nestjs/common';
import { ApiBearerAuth, ApiProduces, ApiTags } from '@nestjs/swagger';
import type { AuthUser } from '../auth/auth-user.js';
import { CurrentUser } from '../auth/decorators/current-user.decorator.js';
import { CreateDeliveryDto, DeliveryFiltersDto, DeliveryQueryDto, UpdateDeliveryDto } from './dto/delivery.dto.js';
import { DeliveriesService } from './deliveries.service.js';

@ApiTags('Deliveries')
@ApiBearerAuth()
@Controller('deliveries')
export class DeliveriesController {
  constructor(private readonly deliveries: DeliveriesService) {}

  /** Paginated list; search matches the reference or customer name */
  @Get()
  list(@Query() query: DeliveryQueryDto) {
    return this.deliveries.list(query);
  }

  /** Counts per status */
  @Get('summary')
  summary() {
    return this.deliveries.summary();
  }

  /** CSV (one row per delivery line) for the same filters as the list */
  @Get('export')
  @ApiProduces('text/csv')
  @Header('Content-Type', 'text/csv; charset=utf-8')
  @Header('Content-Disposition', 'attachment; filename="StockSense_Deliveries.csv"')
  exportCsv(@Query() filters: DeliveryFiltersDto) {
    return this.deliveries.exportCsv(filters);
  }

  @Get(':id')
  findOne(@Param('id', ParseUUIDPipe) id: string) {
    return this.deliveries.findOne(id);
  }

  /** Creates a DRAFT (reference WH/OUT/000001 generated by the database). Stock isn't checked here */
  @Post()
  create(@Body() dto: CreateDeliveryDto, @CurrentUser() user: AuthUser) {
    return this.deliveries.create(dto, user.id);
  }

  /** DRAFT / WAITING only; `items` replaces all lines */
  @Patch(':id')
  update(@Param('id', ParseUUIDPipe) id: string, @Body() dto: UpdateDeliveryDto, @CurrentUser() user: AuthUser) {
    return this.deliveries.update(id, dto, user.id);
  }

  /** DRAFT → READY (in stock) or WAITING (short) */
  @Post(':id/confirm')
  @HttpCode(HttpStatus.OK)
  confirm(@Param('id', ParseUUIDPipe) id: string, @CurrentUser() user: AuthUser) {
    return this.deliveries.confirm(id, user.id);
  }

  /** WAITING → READY when stock is now available */
  @Post(':id/check-availability')
  @HttpCode(HttpStatus.OK)
  checkAvailability(@Param('id', ParseUUIDPipe) id: string, @CurrentUser() user: AuthUser) {
    return this.deliveries.checkAvailability(id, user.id);
  }

  /** Records the pick (READY only; no stock change) */
  @Post(':id/pick')
  @HttpCode(HttpStatus.OK)
  pick(@Param('id', ParseUUIDPipe) id: string, @CurrentUser() user: AuthUser) {
    return this.deliveries.pick(id, user.id);
  }

  /** Records packing (after pick; no stock change) */
  @Post(':id/pack')
  @HttpCode(HttpStatus.OK)
  pack(@Param('id', ParseUUIDPipe) id: string, @CurrentUser() user: AuthUser) {
    return this.deliveries.pack(id, user.id);
  }

  /** READY + picked + packed → DONE: decreases stock (409 INSUFFICIENT_STOCK if short) + ledger, atomically */
  @Post(':id/validate')
  @HttpCode(HttpStatus.OK)
  validate(@Param('id', ParseUUIDPipe) id: string, @CurrentUser() user: AuthUser) {
    return this.deliveries.validate(id, user.id);
  }

  /** DRAFT / WAITING / READY → CANCELED (never after DONE) */
  @Post(':id/cancel')
  @HttpCode(HttpStatus.OK)
  cancel(@Param('id', ParseUUIDPipe) id: string, @CurrentUser() user: AuthUser) {
    return this.deliveries.cancel(id, user.id);
  }
}
