import type { Config } from 'tailwindcss'

// Dashboard theme (Material-style tokens). Its utilities only apply under <html class="ss-dashboard">,
// so its redefined radii/spacing never leak into the other screens.
export default {
  content: ['./src/pages/dashboard/**/*.{ts,tsx}'],
  important: '.ss-dashboard',
  corePlugins: { preflight: false },
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'outline-variant': '#c7c4d8',
        error: '#ba1a1a',
        'on-tertiary-container': '#d9d8ff',
        'primary-fixed-dim': '#c3c0ff',
        'on-tertiary': '#ffffff',
        background: '#f8f9ff',
        'on-secondary-container': '#fefcff',
        'secondary-container': '#2170e4',
        'on-primary-fixed': '#0f0069',
        'on-secondary-fixed': '#001a42',
        'surface-container-high': '#dce9ff',
        'on-tertiary-fixed-variant': '#2f2ebe',
        'on-secondary-fixed-variant': '#004395',
        'surface-container-lowest': '#ffffff',
        'tertiary-container': '#4b4dd8',
        'on-secondary': '#ffffff',
        'on-primary-fixed-variant': '#3323cc',
        'surface-bright': '#f8f9ff',
        'secondary-fixed-dim': '#adc6ff',
        'surface-container': '#e5eeff',
        'on-error': '#ffffff',
        'secondary-fixed': '#d8e2ff',
        'on-primary-container': '#dad7ff',
        surface: '#f8f9ff',
        outline: '#777587',
        'inverse-on-surface': '#eaf1ff',
        'surface-variant': '#d3e4fe',
        primary: '#3525cd',
        'surface-container-highest': '#d3e4fe',
        'primary-fixed': '#e2dfff',
        'surface-tint': '#4d44e3',
        'on-surface-variant': '#464555',
        'on-tertiary-fixed': '#07006c',
        'surface-container-low': '#eff4ff',
        'error-container': '#ffdad6',
        'inverse-primary': '#c3c0ff',
        'primary-container': '#4f46e5',
        'tertiary-fixed': '#e1e0ff',
        'on-surface': '#0b1c30',
        tertiary: '#3130c0',
        'on-error-container': '#93000a',
        'inverse-surface': '#213145',
        'on-background': '#0b1c30',
        secondary: '#0058be',
        'on-primary': '#ffffff',
        'surface-dim': '#cbdbf5',
        'tertiary-fixed-dim': '#c0c1ff',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
      spacing: {
        'space-xl': '1.5rem',
        'space-xs': '0.25rem',
        'margin-mobile': '1rem',
        'gutter-mobile': '0.75rem',
        'space-lg': '1.25rem',
        'space-sm': '0.5rem',
        'space-3xl': '2.5rem',
        'space-base': '1rem',
        'space-2xl': '2rem',
        'margin-desktop': '2rem',
        'space-xxs': '0.125rem',
        'gutter-desktop': '1.5rem',
        'space-md': '0.75rem',
      },
      fontFamily: {
        'headline-lg-mobile': ['Geist', 'Poppins', '-apple-system', 'BlinkMacSystemFont', 'sans-serif'],
        'headline-md': ['Geist', 'Poppins', '-apple-system', 'BlinkMacSystemFont', 'sans-serif'],
        'body-md': ['Geist', 'Poppins', '-apple-system', 'BlinkMacSystemFont', 'sans-serif'],
        'body-sm': ['Geist', 'Poppins', '-apple-system', 'BlinkMacSystemFont', 'sans-serif'],
        'headline-sm': ['Geist', 'Poppins', '-apple-system', 'BlinkMacSystemFont', 'sans-serif'],
        'metric-currency': ['JetBrains Mono'],
        'display-xl': ['Geist', 'Poppins', '-apple-system', 'BlinkMacSystemFont', 'sans-serif'],
        'metric-tabular-sm': ['JetBrains Mono'],
        'body-lg': ['Geist', 'Poppins', '-apple-system', 'BlinkMacSystemFont', 'sans-serif'],
        'label-md': ['Geist', 'Poppins', '-apple-system', 'BlinkMacSystemFont', 'sans-serif'],
        'headline-lg': ['Geist', 'Poppins', '-apple-system', 'BlinkMacSystemFont', 'sans-serif'],
        'label-sm': ['Geist', 'Poppins', '-apple-system', 'BlinkMacSystemFont', 'sans-serif'],
      },
      fontSize: {
        'headline-lg-mobile': ['24px', { lineHeight: '32px', letterSpacing: '-0.015em', fontWeight: '700' }],
        'headline-md': ['20px', { lineHeight: '28px', letterSpacing: '-0.015em', fontWeight: '600' }],
        'body-md': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'body-sm': ['12px', { lineHeight: '16px', fontWeight: '400' }],
        'headline-sm': ['16px', { lineHeight: '24px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'metric-currency': ['24px', { lineHeight: '32px', letterSpacing: '-0.03em', fontWeight: '600' }],
        'display-xl': ['36px', { lineHeight: '44px', letterSpacing: '-0.025em', fontWeight: '700' }],
        'metric-tabular-sm': ['13px', { lineHeight: '16px', fontWeight: '500' }],
        'body-lg': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'label-md': ['13px', { lineHeight: '18px', fontWeight: '500' }],
        'headline-lg': ['28px', { lineHeight: '36px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'label-sm': ['11px', { lineHeight: '14px', letterSpacing: '0.04em', fontWeight: '600' }],
      },
    },
  },
} satisfies Config
