import { Body, Controller, Get, Header, HttpCode, HttpStatus, Param, ParseUUIDPipe, Patch, Post, Query } from '@nestjs/common';
import { ApiBearerAuth, ApiProduces, ApiTags } from '@nestjs/swagger';
import type { AuthUser } from '../auth/auth-user.js';
import { CurrentUser } from '../auth/decorators/current-user.decorator.js';
import { CreateReceiptDto, ReceiptFiltersDto, ReceiptQueryDto, UpdateReceiptDto } from './dto/receipt.dto.js';
import { ReceiptsService } from './receipts.service.js';

@ApiTags('Receipts')
@ApiBearerAuth()
@Controller('receipts')
export class ReceiptsController {
  constructor(private readonly receipts: ReceiptsService) {}

  /** Paginated list; search matches the reference or supplier name */
  @Get()
  list(@Query() query: ReceiptQueryDto) {
    return this.receipts.list(query);
  }

  /** Counts per status */
  @Get('summary')
  summary() {
    return this.receipts.summary();
  }

  /** CSV (one row per receipt line) for the same filters as the list */
  @Get('export')
  @ApiProduces('text/csv')
  @Header('Content-Type', 'text/csv; charset=utf-8')
  @Header('Content-Disposition', 'attachment; filename="StockSense_Receipts.csv"')
  exportCsv(@Query() filters: ReceiptFiltersDto) {
    return this.receipts.exportCsv(filters);
  }

  @Get(':id')
  findOne(@Param('id', ParseUUIDPipe) id: string) {
    return this.receipts.findOne(id);
  }

  /** Creates a DRAFT; the reference (WH/IN/000001) is generated by the database */
  @Post()
  create(@Body() dto: CreateReceiptDto, @CurrentUser() user: AuthUser) {
    return this.receipts.create(dto, user.id);
  }

  /** DRAFT / WAITING only; `items` replaces all lines */
  @Patch(':id')
  update(@Param('id', ParseUUIDPipe) id: string, @Body() dto: UpdateReceiptDto, @CurrentUser() user: AuthUser) {
    return this.receipts.update(id, dto, user.id);
  }

  /** DRAFT → WAITING */
  @Post(':id/confirm')
  @HttpCode(HttpStatus.OK)
  confirm(@Param('id', ParseUUIDPipe) id: string, @CurrentUser() user: AuthUser) {
    return this.receipts.confirm(id, user.id);
  }

  /** WAITING → READY */
  @Post(':id/ready')
  @HttpCode(HttpStatus.OK)
  markReady(@Param('id', ParseUUIDPipe) id: string, @CurrentUser() user: AuthUser) {
    return this.receipts.markReady(id, user.id);
  }

  /** READY → DONE: increases stock for every line and writes the ledger, atomically */
  @Post(':id/validate')
  @HttpCode(HttpStatus.OK)
  validate(@Param('id', ParseUUIDPipe) id: string, @CurrentUser() user: AuthUser) {
    return this.receipts.validate(id, user.id);
  }

  /** DRAFT / WAITING / READY → CANCELED (never after DONE) */
  @Post(':id/cancel')
  @HttpCode(HttpStatus.OK)
  cancel(@Param('id', ParseUUIDPipe) id: string, @CurrentUser() user: AuthUser) {
    return this.receipts.cancel(id, user.id);
  }
}
