// Shapes returned by the StockSense API (backend/src/**)

export type UserRole = 'INVENTORY_MANAGER' | 'WAREHOUSE_STAFF'
export type RecordStatus = 'ACTIVE' | 'INACTIVE'
export type StockStatus = 'IN_STOCK' | 'LOW_STOCK' | 'OUT_OF_STOCK'

export interface UserProfile {
  id: string
  fullName: string
  email: string
  phone: string | null
  role: UserRole
  status: RecordStatus
  createdAt: string
  lastLoginAt: string | null
}

export interface AuthResponse {
  accessToken: string
  refreshToken: string
  user: UserProfile
}

export interface MessageResponse {
  message: string
}

export interface Paginated<T> {
  data: T[]
  pagination: {
    page: number
    limit: number
    total: number
    totalPages: number
  }
}

export interface Category {
  id: string
  name: string
  description: string | null
  status: RecordStatus
  productCount: number
  createdAt: string
  updatedAt: string
}

export interface ProductStockLocation {
  locationId: string
  locationName: string
  locationCode: string
  warehouseId: string
  warehouseName: string
  quantity: number
}

export interface Product {
  id: string
  name: string
  sku: string
  unitOfMeasure: string
  reorderLevel: number
  status: RecordStatus
  category: { id: string; name: string; status: RecordStatus }
  createdBy: { id: string; fullName: string }
  createdAt: string
  updatedAt: string
  stock: {
    onHand: number
    stockStatus: StockStatus
    locationCount: number
    locations: ProductStockLocation[]
  }
}

export interface ProductSummary {
  totalProducts: number
  inStock: number
  lowStock: number
  outOfStock: number
  warehouses: number
}

export const ROLE_LABEL: Record<UserRole, string> = {
  INVENTORY_MANAGER: 'Inventory Manager',
  WAREHOUSE_STAFF: 'Warehouse Staff',
}

export const STOCK_STATUS_LABEL: Record<StockStatus, string> = {
  IN_STOCK: 'In Stock',
  LOW_STOCK: 'Low Stock',
  OUT_OF_STOCK: 'Out of Stock',
}

export interface WarehouseLocation {
  id: string
  name: string
  code: string
  status: RecordStatus
  /** Distinct products currently stocked here */
  productCount: number
  createdAt: string
  updatedAt: string
}

export interface Warehouse {
  id: string
  name: string
  code: string
  /** Address or notes */
  description: string | null
  status: RecordStatus
  createdBy: { id: string; fullName: string }
  createdAt: string
  updatedAt: string
  locationCount: number
  activeLocationCount: number
  /** Distinct products currently stocked anywhere in the warehouse */
  productCount: number
  locations: WarehouseLocation[]
}

export interface WarehouseSummary {
  totalWarehouses: number
  activeWarehouses: number
  totalLocations: number
  activeLocations: number
  storedProducts: number
  topWarehouse: { id: string; name: string; code: string; productCount: number } | null
}

/** A location with its warehouse (from /locations) */
export interface Location {
  id: string
  name: string
  code: string
  status: RecordStatus
  warehouse: { id: string; name: string; code: string; status: RecordStatus }
  productCount: number
  createdAt: string
  updatedAt: string
}

/** One stock position: a product at a location */
export interface StockPosition {
  stockId: string
  quantity: number
  version: number
  updatedAt: string
  product: {
    id: string
    name: string
    sku: string
    unitOfMeasure: string
    reorderLevel: number
    status: RecordStatus
    category: { id: string; name: string }
    totalQuantity: number
    stockStatus: StockStatus
  }
  location: { id: string; name: string; code: string; status: RecordStatus }
  warehouse: { id: string; name: string; code: string; status: RecordStatus }
}

export interface ProductStockLevel {
  productId: string
  productName: string
  sku: string
  unitOfMeasure: string
  category: string
  currentQuantity: number
  reorderLevel: number
  status: StockStatus
}

/** What a delivery can take from one location, or the basis for an adjustment */
export interface AvailableStock {
  productId: string
  locationId: string
  unitOfMeasure: string
  quantity: number
  version: number
}

export type DocumentStatus = 'DRAFT' | 'WAITING' | 'READY' | 'DONE' | 'CANCELED'

export const DOCUMENT_STATUS_LABEL: Record<DocumentStatus, string> = {
  DRAFT: 'Draft',
  WAITING: 'Waiting',
  READY: 'Ready',
  DONE: 'Done',
  CANCELED: 'Canceled',
}

export interface Supplier {
  id: string
  name: string
  code: string | null
  email: string | null
  phone: string | null
  status: RecordStatus
  receiptCount: number
  createdAt: string
  updatedAt: string
}

export interface ReceiptItem {
  id: string
  productId: string
  productName: string
  sku: string
  unitOfMeasure: string
  quantity: number
}

export interface Receipt {
  id: string
  /** Generated by the backend, e.g. WH/IN/000001 */
  reference: string
  status: DocumentStatus
  receiptDate: string
  supplier: { id: string; name: string; code: string | null; status: RecordStatus }
  warehouse: { id: string; name: string; code: string }
  location: { id: string; name: string; code: string }
  items: ReceiptItem[]
  lineCount: number
  totalQuantity: number
  createdBy: { id: string; fullName: string }
  validatedBy: { id: string; fullName: string } | null
  validatedAt: string | null
  createdAt: string
  updatedAt: string
}

export interface ReceiptStockChange {
  productId: string
  sku: string
  unitOfMeasure: string
  quantity: number
  before: number
  after: number
}

export type ReceiptSummary = Record<DocumentStatus, number> & { total: number }

export interface Customer {
  id: string
  name: string
  code: string | null
  email: string | null
  phone: string | null
  status: RecordStatus
  deliveryCount: number
  createdAt: string
  updatedAt: string
}

export interface DeliveryItem {
  id: string
  productId: string
  productName: string
  sku: string
  unitOfMeasure: string
  quantity: number
  /** Current stock at the source location (advisory; validation re-checks under lock) */
  available: number
  shortage: number
}

export interface Delivery {
  id: string
  /** Generated by the backend, e.g. WH/OUT/000001 */
  reference: string
  status: DocumentStatus
  deliveryDate: string
  customer: { id: string; name: string; code: string | null; status: RecordStatus }
  warehouse: { id: string; name: string; code: string }
  sourceLocation: { id: string; name: string; code: string }
  items: DeliveryItem[]
  lineCount: number
  totalQuantity: number
  /** Every line currently has enough stock at the source location */
  isAvailable: boolean
  picked: { by: { id: string; fullName: string }; at: string } | null
  packed: { by: { id: string; fullName: string }; at: string } | null
  createdBy: { id: string; fullName: string }
  validatedBy: { id: string; fullName: string } | null
  validatedAt: string | null
  createdAt: string
  updatedAt: string
}

export interface StockChangeLine {
  productId: string
  sku: string
  unitOfMeasure: string
  quantity: number
  before: number
  after: number
}

export type DeliverySummary = Record<DocumentStatus, number> & { total: number }

export interface TransferItem {
  id: string
  productId: string
  productName: string
  sku: string
  unitOfMeasure: string
  quantity: number
  /** Current stock at the source location (advisory; validation re-checks under lock) */
  available: number
  shortage: number
}

export interface Transfer {
  id: string
  /** Generated by the backend, e.g. WH/TR/000001 */
  reference: string
  status: DocumentStatus
  transferDate: string
  sourceWarehouse: { id: string; name: string; code: string }
  sourceLocation: { id: string; name: string; code: string }
  destinationWarehouse: { id: string; name: string; code: string }
  destinationLocation: { id: string; name: string; code: string }
  items: TransferItem[]
  lineCount: number
  totalQuantity: number
  isAvailable: boolean
  createdBy: { id: string; fullName: string }
  validatedBy: { id: string; fullName: string } | null
  validatedAt: string | null
  createdAt: string
  updatedAt: string
}

export interface TransferStockChange {
  productId: string
  sku: string
  unitOfMeasure: string
  quantity: number
  source: { before: number; after: number }
  destination: { before: number; after: number }
}

export type TransferSummary = Record<DocumentStatus, number> & { total: number }

export interface Adjustment {
  id: string
  /** Generated by the backend, e.g. WH/ADJ/000001 */
  reference: string
  /** DRAFT → DONE, or CANCELED */
  status: DocumentStatus
  product: { id: string; name: string; sku: string; unitOfMeasure: string }
  warehouse: { id: string; name: string; code: string }
  location: { id: string; name: string; code: string }
  /** Read by the backend from current stock when drafted (never entered by the user) */
  recordedQuantity: number
  recordedStockVersion: number
  physicalQuantity: number
  /** physical − recorded */
  difference: number
  reason: string
  notes: string | null
  /** Live stock now */
  currentQuantity: number
  /** DRAFT whose stock moved since it was recorded: apply would fail (STALE_STOCK) until refreshed */
  isStale: boolean
  createdBy: { id: string; fullName: string }
  appliedBy: { id: string; fullName: string } | null
  appliedAt: string | null
  createdAt: string
  updatedAt: string
}

export type AdjustmentSummary = Record<DocumentStatus, number> & { total: number }

export type MovementType = 'RECEIPT' | 'DELIVERY' | 'INTERNAL_TRANSFER' | 'ADJUSTMENT'
export type LedgerDirection = 'IN' | 'OUT' | 'TRANSFER' | 'ADJUSTMENT_IN' | 'ADJUSTMENT_OUT'

export interface LedgerPlace {
  id: string
  name: string
  code: string
}

/** One append-only stock ledger row (written only when a document is validated / applied) */
export interface LedgerEntry {
  id: string
  createdAt: string
  movementType: MovementType
  direction: LedgerDirection
  /** Magnitude */
  quantity: number
  /** +quantity for IN / ADJUSTMENT_IN, -quantity for OUT / ADJUSTMENT_OUT */
  signedQuantity: number
  quantityBefore: number | null
  quantityAfter: number | null
  product: { id: string; name: string; sku: string; unitOfMeasure: string }
  warehouse: LedgerPlace
  location: LedgerPlace
  sourceLocation: LedgerPlace | null
  destinationLocation: LedgerPlace | null
  /** The receipt / delivery / transfer / adjustment that caused the movement */
  referenceType: MovementType
  referenceId: string
  /** Document reference, e.g. WH/IN/000001 */
  reference: string
  performedBy: { id: string; name: string }
}

export interface LedgerSummary {
  totalMovements: number
  byMovementType: Record<MovementType, number>
}

/**
 * Dashboard KPIs. Stock KPIs follow the warehouse / location / category filters; the pending-document
 * KPIs follow warehouse / location / category / status / date. Document type only narrows the operations list.
 */
export interface DashboardSummary {
  /** Distinct active products with stock > 0 (in the filtered scope) */
  totalProductsInStock: number
  /** Active products in the category filter */
  totalProducts: number
  /** 0 < stock <= reorder level */
  lowStock: number
  /** stock = 0 */
  outOfStock: number
  /** DRAFT / WAITING / READY (narrowed to the status filter when it is one of these) */
  pendingReceipts: number
  pendingDeliveries: number
  internalTransfersScheduled: number
  pendingAdjustments: number
  /** Active categories / warehouses (not filtered) */
  categories: number
  warehouses: number
}

export interface DashboardFilterValues {
  documentType: MovementType | null
  status: DocumentStatus | null
  warehouseId: string | null
  locationId: string | null
  categoryId: string | null
  dateFrom: string | null
  dateTo: string | null
}

export interface DashboardResponse {
  summary: DashboardSummary
  /** The filters the backend applied (null = not set) */
  filters: DashboardFilterValues
}

/** A low / out-of-stock product; quantity is summed over the filtered warehouse / location */
export interface StockAlert {
  product: { id: string; name: string; sku: string; unitOfMeasure: string }
  category: { id: string; name: string }
  reorderLevel: number
  quantity: number
  status: 'LOW_STOCK' | 'OUT_OF_STOCK'
}

/** One document line: a product on a receipt / delivery / transfer, or one adjustment */
export interface OperationRow {
  documentType: MovementType
  documentId: string
  reference: string
  status: DocumentStatus
  date: string
  createdAt: string
  product: { id: string; name: string; sku: string; unitOfMeasure: string }
  category: { id: string; name: string }
  /** Receipt / adjustment location, delivery / transfer source */
  location: { warehouseName: string; locationName: string }
  /** Transfers only */
  destination: { warehouseName: string; locationName: string } | null
  /** Supplier (receipts), customer (deliveries) or reason (adjustments) */
  partner: string | null
  /** Line quantity; adjustments: signed difference */
  quantity: number
}
