-- =====================================================================
-- StockSense — Inventory Management System
-- 001: core schema (PostgreSQL)
--
-- Products define what exists. Warehouses and locations define where it
-- exists. Stock defines how much currently exists there. Receipts,
-- deliveries, transfers and adjustments are the only operations that
-- change stock, and every stock mutation writes an immutable ledger row
-- in the same transaction.
-- =====================================================================

CREATE EXTENSION IF NOT EXISTS pgcrypto; -- gen_random_uuid()

-- ---------------------------------------------------------------------
-- Enums
-- ---------------------------------------------------------------------
CREATE TYPE user_role AS ENUM ('INVENTORY_MANAGER', 'WAREHOUSE_STAFF');

-- Users, products, warehouses, locations, suppliers, customers
CREATE TYPE record_status AS ENUM ('ACTIVE', 'INACTIVE');

-- Receipts, deliveries, transfers, adjustments
CREATE TYPE document_status AS ENUM ('DRAFT', 'WAITING', 'READY', 'DONE', 'CANCELED');

-- Used for both stock_ledger.movement_type and stock_ledger.reference_type
CREATE TYPE inventory_operation AS ENUM ('RECEIPT', 'DELIVERY', 'INTERNAL_TRANSFER', 'ADJUSTMENT');

CREATE TYPE ledger_direction AS ENUM ('IN', 'OUT', 'TRANSFER', 'ADJUSTMENT_IN', 'ADJUSTMENT_OUT');

-- ---------------------------------------------------------------------
-- Shared trigger: keep updated_at current
-- ---------------------------------------------------------------------
CREATE FUNCTION set_updated_at() RETURNS trigger
LANGUAGE plpgsql AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$;

-- ---------------------------------------------------------------------
-- Document reference sequences (WH/IN/000001 …), generated by the database
-- ---------------------------------------------------------------------
CREATE SEQUENCE receipt_reference_seq;
CREATE SEQUENCE delivery_reference_seq;
CREATE SEQUENCE transfer_reference_seq;
CREATE SEQUENCE adjustment_reference_seq;

-- =====================================================================
-- AUTHENTICATION
-- =====================================================================

-- 01. users
CREATE TABLE users (
  id             UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  full_name      VARCHAR(150) NOT NULL,
  email          VARCHAR(255) NOT NULL,
  phone          VARCHAR(30),                 -- "Direct Contact" on the Profile screen
  password_hash  TEXT NOT NULL,               -- never the plaintext password
  role           user_role NOT NULL DEFAULT 'WAREHOUSE_STAFF',
  status         record_status NOT NULL DEFAULT 'ACTIVE',
  created_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
  last_login_at  TIMESTAMPTZ,
  CONSTRAINT users_email_lowercase CHECK (email = lower(email))
);
CREATE UNIQUE INDEX users_email_key ON users (email);

-- 02. password_reset_otps
CREATE TABLE password_reset_otps (
  id             UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id        UUID NOT NULL REFERENCES users (id) ON DELETE CASCADE,
  otp_hash       TEXT NOT NULL,               -- never the OTP itself
  expires_at     TIMESTAMPTZ NOT NULL,
  verified_at    TIMESTAMPTZ,
  attempt_count  INTEGER NOT NULL DEFAULT 0 CHECK (attempt_count >= 0),
  used_at        TIMESTAMPTZ,
  created_at     TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX password_reset_otps_user_created_idx ON password_reset_otps (user_id, created_at DESC);

-- =====================================================================
-- MASTER DATA
-- =====================================================================

-- 03. categories
CREATE TABLE categories (
  id           UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  name         VARCHAR(100) NOT NULL UNIQUE,
  description  TEXT,
  created_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at   TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- 04. products (no stock columns: stock lives per location in `stock`)
CREATE TABLE products (
  id               UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  name             VARCHAR(200) NOT NULL,
  sku              VARCHAR(100) NOT NULL UNIQUE,
  category_id      UUID NOT NULL REFERENCES categories (id) ON DELETE RESTRICT,
  unit_of_measure  VARCHAR(30) NOT NULL,
  reorder_level    NUMERIC(18,3) NOT NULL DEFAULT 0 CHECK (reorder_level >= 0),
  status           record_status NOT NULL DEFAULT 'ACTIVE',
  created_at       TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at       TIMESTAMPTZ NOT NULL DEFAULT now(),
  created_by       UUID NOT NULL REFERENCES users (id) ON DELETE RESTRICT,
  updated_by       UUID REFERENCES users (id) ON DELETE RESTRICT
);
CREATE INDEX products_name_idx ON products (name);
CREATE INDEX products_category_id_idx ON products (category_id);
CREATE INDEX products_status_idx ON products (status);

-- 05. warehouses
CREATE TABLE warehouses (
  id           UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  name         VARCHAR(150) NOT NULL,
  code         VARCHAR(50) NOT NULL UNIQUE,
  description  TEXT,
  status       record_status NOT NULL DEFAULT 'ACTIVE',
  created_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
  created_by   UUID NOT NULL REFERENCES users (id) ON DELETE RESTRICT,
  updated_by   UUID REFERENCES users (id) ON DELETE RESTRICT
);
CREATE INDEX warehouses_status_idx ON warehouses (status);

-- 06. locations (each belongs to exactly one warehouse)
CREATE TABLE locations (
  id            UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  warehouse_id  UUID NOT NULL REFERENCES warehouses (id) ON DELETE RESTRICT,
  name          VARCHAR(150) NOT NULL,
  code          VARCHAR(50) NOT NULL,
  status        record_status NOT NULL DEFAULT 'ACTIVE',
  created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT locations_warehouse_code_key UNIQUE (warehouse_id, code),
  -- Target for composite FKs that prove "this location belongs to this warehouse"
  CONSTRAINT locations_id_warehouse_key UNIQUE (id, warehouse_id)
);
CREATE INDEX locations_warehouse_id_idx ON locations (warehouse_id);
CREATE INDEX locations_status_idx ON locations (status);

-- 07. suppliers
CREATE TABLE suppliers (
  id          UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  name        VARCHAR(200) NOT NULL,
  code        VARCHAR(50) UNIQUE,
  email       VARCHAR(255),
  phone       VARCHAR(30),
  status      record_status NOT NULL DEFAULT 'ACTIVE',
  created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX suppliers_name_idx ON suppliers (name);

-- 08. customers
CREATE TABLE customers (
  id          UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  name        VARCHAR(200) NOT NULL,
  code        VARCHAR(50) UNIQUE,
  email       VARCHAR(255),
  phone       VARCHAR(30),
  status      record_status NOT NULL DEFAULT 'ACTIVE',
  created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX customers_name_idx ON customers (name);

-- =====================================================================
-- INVENTORY: current state
-- =====================================================================

-- 09. stock (one row per product + location)
CREATE TABLE stock (
  id           UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  product_id   UUID NOT NULL REFERENCES products (id) ON DELETE RESTRICT,
  location_id  UUID NOT NULL REFERENCES locations (id) ON DELETE RESTRICT,
  quantity     NUMERIC(18,3) NOT NULL DEFAULT 0 CHECK (quantity >= 0),
  version      INTEGER NOT NULL DEFAULT 0,   -- bumped on every change (optimistic check for adjustments)
  created_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT stock_product_location_key UNIQUE (product_id, location_id)
);
CREATE INDEX stock_product_id_idx ON stock (product_id);
CREATE INDEX stock_location_id_idx ON stock (location_id);

-- =====================================================================
-- RECEIVING
-- =====================================================================

-- 10. receipts
CREATE TABLE receipts (
  id            UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  reference     VARCHAR(50) NOT NULL UNIQUE
                DEFAULT ('WH/IN/' || lpad(nextval('receipt_reference_seq')::text, 6, '0')),
  supplier_id   UUID NOT NULL REFERENCES suppliers (id) ON DELETE RESTRICT,
  warehouse_id  UUID NOT NULL REFERENCES warehouses (id) ON DELETE RESTRICT,
  location_id   UUID NOT NULL,
  status        document_status NOT NULL DEFAULT 'DRAFT',
  receipt_date  TIMESTAMPTZ NOT NULL DEFAULT now(),
  created_by    UUID NOT NULL REFERENCES users (id) ON DELETE RESTRICT,
  updated_by    UUID REFERENCES users (id) ON DELETE RESTRICT,
  validated_by  UUID REFERENCES users (id) ON DELETE RESTRICT,
  validated_at  TIMESTAMPTZ,
  created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT receipts_location_in_warehouse_fk
    FOREIGN KEY (location_id, warehouse_id) REFERENCES locations (id, warehouse_id) ON DELETE RESTRICT,
  CONSTRAINT receipts_done_is_validated
    CHECK (status <> 'DONE' OR (validated_by IS NOT NULL AND validated_at IS NOT NULL))
);
CREATE INDEX receipts_status_idx ON receipts (status);
CREATE INDEX receipts_supplier_id_idx ON receipts (supplier_id);
CREATE INDEX receipts_warehouse_id_idx ON receipts (warehouse_id);
CREATE INDEX receipts_location_id_idx ON receipts (location_id);
CREATE INDEX receipts_receipt_date_idx ON receipts (receipt_date);

-- 11. receipt_items
CREATE TABLE receipt_items (
  id          UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  receipt_id  UUID NOT NULL REFERENCES receipts (id) ON DELETE CASCADE,
  product_id  UUID NOT NULL REFERENCES products (id) ON DELETE RESTRICT,
  quantity    NUMERIC(18,3) NOT NULL CHECK (quantity > 0),
  created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT receipt_items_receipt_product_key UNIQUE (receipt_id, product_id)
);
CREATE INDEX receipt_items_product_id_idx ON receipt_items (product_id);

-- =====================================================================
-- DELIVERY
-- =====================================================================

-- 12. deliveries
CREATE TABLE deliveries (
  id                  UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  reference           VARCHAR(50) NOT NULL UNIQUE
                      DEFAULT ('WH/OUT/' || lpad(nextval('delivery_reference_seq')::text, 6, '0')),
  customer_id         UUID NOT NULL REFERENCES customers (id) ON DELETE RESTRICT,
  warehouse_id        UUID NOT NULL REFERENCES warehouses (id) ON DELETE RESTRICT,
  source_location_id  UUID NOT NULL,
  status              document_status NOT NULL DEFAULT 'DRAFT',
  delivery_date       TIMESTAMPTZ NOT NULL DEFAULT now(),
  created_by          UUID NOT NULL REFERENCES users (id) ON DELETE RESTRICT,
  updated_by          UUID REFERENCES users (id) ON DELETE RESTRICT,
  picked_by           UUID REFERENCES users (id) ON DELETE RESTRICT,
  picked_at           TIMESTAMPTZ,
  packed_by           UUID REFERENCES users (id) ON DELETE RESTRICT,
  packed_at           TIMESTAMPTZ,
  validated_by        UUID REFERENCES users (id) ON DELETE RESTRICT,
  validated_at        TIMESTAMPTZ,
  created_at          TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at          TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT deliveries_location_in_warehouse_fk
    FOREIGN KEY (source_location_id, warehouse_id) REFERENCES locations (id, warehouse_id) ON DELETE RESTRICT,
  CONSTRAINT deliveries_pack_after_pick CHECK (packed_at IS NULL OR picked_at IS NOT NULL),
  CONSTRAINT deliveries_done_is_validated
    CHECK (status <> 'DONE' OR (validated_by IS NOT NULL AND validated_at IS NOT NULL))
);
CREATE INDEX deliveries_status_idx ON deliveries (status);
CREATE INDEX deliveries_customer_id_idx ON deliveries (customer_id);
CREATE INDEX deliveries_warehouse_id_idx ON deliveries (warehouse_id);
CREATE INDEX deliveries_source_location_id_idx ON deliveries (source_location_id);
CREATE INDEX deliveries_delivery_date_idx ON deliveries (delivery_date);

-- 13. delivery_items
CREATE TABLE delivery_items (
  id           UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  delivery_id  UUID NOT NULL REFERENCES deliveries (id) ON DELETE CASCADE,
  product_id   UUID NOT NULL REFERENCES products (id) ON DELETE RESTRICT,
  quantity     NUMERIC(18,3) NOT NULL CHECK (quantity > 0),
  created_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT delivery_items_delivery_product_key UNIQUE (delivery_id, product_id)
);
CREATE INDEX delivery_items_product_id_idx ON delivery_items (product_id);

-- =====================================================================
-- INTERNAL TRANSFER
-- =====================================================================

-- 14. internal_transfers
CREATE TABLE internal_transfers (
  id                        UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  reference                 VARCHAR(50) NOT NULL UNIQUE
                            DEFAULT ('WH/TR/' || lpad(nextval('transfer_reference_seq')::text, 6, '0')),
  source_warehouse_id       UUID NOT NULL REFERENCES warehouses (id) ON DELETE RESTRICT,
  source_location_id        UUID NOT NULL,
  destination_warehouse_id  UUID NOT NULL REFERENCES warehouses (id) ON DELETE RESTRICT,
  destination_location_id   UUID NOT NULL,
  status                    document_status NOT NULL DEFAULT 'DRAFT',
  transfer_date             TIMESTAMPTZ NOT NULL DEFAULT now(),
  created_by                UUID NOT NULL REFERENCES users (id) ON DELETE RESTRICT,
  updated_by                UUID REFERENCES users (id) ON DELETE RESTRICT,
  validated_by              UUID REFERENCES users (id) ON DELETE RESTRICT,
  validated_at              TIMESTAMPTZ,
  created_at                TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at                TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT internal_transfers_source_in_warehouse_fk
    FOREIGN KEY (source_location_id, source_warehouse_id) REFERENCES locations (id, warehouse_id) ON DELETE RESTRICT,
  CONSTRAINT internal_transfers_destination_in_warehouse_fk
    FOREIGN KEY (destination_location_id, destination_warehouse_id) REFERENCES locations (id, warehouse_id) ON DELETE RESTRICT,
  CONSTRAINT internal_transfers_distinct_locations CHECK (source_location_id <> destination_location_id),
  CONSTRAINT internal_transfers_done_is_validated
    CHECK (status <> 'DONE' OR (validated_by IS NOT NULL AND validated_at IS NOT NULL))
);
CREATE INDEX internal_transfers_status_idx ON internal_transfers (status);
CREATE INDEX internal_transfers_source_location_id_idx ON internal_transfers (source_location_id);
CREATE INDEX internal_transfers_destination_location_id_idx ON internal_transfers (destination_location_id);
CREATE INDEX internal_transfers_transfer_date_idx ON internal_transfers (transfer_date);

-- 15. internal_transfer_items
CREATE TABLE internal_transfer_items (
  id           UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  transfer_id  UUID NOT NULL REFERENCES internal_transfers (id) ON DELETE CASCADE,
  product_id   UUID NOT NULL REFERENCES products (id) ON DELETE RESTRICT,
  quantity     NUMERIC(18,3) NOT NULL CHECK (quantity > 0),
  created_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT internal_transfer_items_transfer_product_key UNIQUE (transfer_id, product_id)
);
CREATE INDEX internal_transfer_items_product_id_idx ON internal_transfer_items (product_id);

-- =====================================================================
-- ADJUSTMENT
-- =====================================================================

-- 16. inventory_adjustments
CREATE TABLE inventory_adjustments (
  id                      UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  reference               VARCHAR(50) NOT NULL UNIQUE
                          DEFAULT ('WH/ADJ/' || lpad(nextval('adjustment_reference_seq')::text, 6, '0')),
  product_id              UUID NOT NULL REFERENCES products (id) ON DELETE RESTRICT,
  warehouse_id            UUID NOT NULL REFERENCES warehouses (id) ON DELETE RESTRICT,
  location_id             UUID NOT NULL,
  recorded_quantity       NUMERIC(18,3) NOT NULL CHECK (recorded_quantity >= 0),
  recorded_stock_version  INTEGER NOT NULL DEFAULT 0, -- stock.version when recorded_quantity was read
  physical_quantity       NUMERIC(18,3) NOT NULL CHECK (physical_quantity >= 0),
  difference              NUMERIC(18,3) NOT NULL,
  reason                  VARCHAR(255) NOT NULL,
  notes                   TEXT,
  status                  document_status NOT NULL DEFAULT 'DRAFT',
  created_by              UUID NOT NULL REFERENCES users (id) ON DELETE RESTRICT,
  updated_by              UUID REFERENCES users (id) ON DELETE RESTRICT,
  applied_by              UUID REFERENCES users (id) ON DELETE RESTRICT,
  applied_at              TIMESTAMPTZ,
  created_at              TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at              TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT inventory_adjustments_location_in_warehouse_fk
    FOREIGN KEY (location_id, warehouse_id) REFERENCES locations (id, warehouse_id) ON DELETE RESTRICT,
  CONSTRAINT inventory_adjustments_difference_matches
    CHECK (difference = physical_quantity - recorded_quantity),
  CONSTRAINT inventory_adjustments_done_is_applied
    CHECK (status <> 'DONE' OR (applied_by IS NOT NULL AND applied_at IS NOT NULL))
);
CREATE INDEX inventory_adjustments_status_idx ON inventory_adjustments (status);
CREATE INDEX inventory_adjustments_product_id_idx ON inventory_adjustments (product_id);
CREATE INDEX inventory_adjustments_location_id_idx ON inventory_adjustments (location_id);
CREATE INDEX inventory_adjustments_created_at_idx ON inventory_adjustments (created_at);

-- =====================================================================
-- AUDIT / HISTORY
-- =====================================================================

-- 17. stock_ledger (append-only; one row per affected location)
CREATE TABLE stock_ledger (
  id                       UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  product_id               UUID NOT NULL REFERENCES products (id) ON DELETE RESTRICT,
  warehouse_id             UUID NOT NULL REFERENCES warehouses (id) ON DELETE RESTRICT,
  location_id              UUID NOT NULL,
  movement_type            inventory_operation NOT NULL,
  direction                ledger_direction NOT NULL,
  quantity                 NUMERIC(18,3) NOT NULL CHECK (quantity > 0), -- magnitude; direction gives the sign
  source_location_id       UUID REFERENCES locations (id) ON DELETE RESTRICT,
  destination_location_id  UUID REFERENCES locations (id) ON DELETE RESTRICT,
  reference_type           inventory_operation NOT NULL,
  reference_id             UUID NOT NULL,        -- id of the receipt / delivery / transfer / adjustment
  reference_code           VARCHAR(50) NOT NULL, -- its human-readable reference (WH/IN/000001) for display
  quantity_before          NUMERIC(18,3) CHECK (quantity_before >= 0),
  quantity_after           NUMERIC(18,3) CHECK (quantity_after >= 0),
  performed_by             UUID NOT NULL REFERENCES users (id) ON DELETE RESTRICT,
  created_at               TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT stock_ledger_location_in_warehouse_fk
    FOREIGN KEY (location_id, warehouse_id) REFERENCES locations (id, warehouse_id) ON DELETE RESTRICT,
  CONSTRAINT stock_ledger_balance_matches CHECK (
    quantity_before IS NULL OR quantity_after IS NULL OR
    quantity_after = quantity_before + CASE WHEN direction IN ('OUT', 'ADJUSTMENT_OUT') THEN -quantity ELSE quantity END
  )
);
CREATE INDEX stock_ledger_product_id_idx ON stock_ledger (product_id);
CREATE INDEX stock_ledger_location_id_idx ON stock_ledger (location_id);
CREATE INDEX stock_ledger_movement_type_idx ON stock_ledger (movement_type);
CREATE INDEX stock_ledger_created_at_idx ON stock_ledger (created_at DESC);
CREATE INDEX stock_ledger_reference_id_idx ON stock_ledger (reference_id);

-- The ledger is history: the application may only INSERT
CREATE FUNCTION stock_ledger_is_append_only() RETURNS trigger
LANGUAGE plpgsql AS $$
BEGIN
  RAISE EXCEPTION 'stock_ledger is append-only: % is not allowed', TG_OP;
END;
$$;

CREATE TRIGGER stock_ledger_no_update_delete
  BEFORE UPDATE OR DELETE ON stock_ledger
  FOR EACH ROW EXECUTE FUNCTION stock_ledger_is_append_only();

CREATE TRIGGER stock_ledger_no_truncate
  BEFORE TRUNCATE ON stock_ledger
  FOR EACH STATEMENT EXECUTE FUNCTION stock_ledger_is_append_only();

-- ---------------------------------------------------------------------
-- updated_at triggers
-- ---------------------------------------------------------------------
DO $$
DECLARE
  t TEXT;
BEGIN
  FOREACH t IN ARRAY ARRAY[
    'users', 'categories', 'products', 'warehouses', 'locations', 'suppliers', 'customers', 'stock',
    'receipts', 'receipt_items', 'deliveries', 'delivery_items',
    'internal_transfers', 'internal_transfer_items', 'inventory_adjustments'
  ] LOOP
    EXECUTE format('CREATE TRIGGER %I_set_updated_at BEFORE UPDATE ON %I FOR EACH ROW EXECUTE FUNCTION set_updated_at()', t, t);
  END LOOP;
END;
$$;
