import { Body, Controller, Get, Header, HttpCode, HttpStatus, Param, ParseUUIDPipe, Patch, Post, Query } from '@nestjs/common';
import { ApiBearerAuth, ApiProduces, ApiTags } from '@nestjs/swagger';
import type { AuthUser } from '../auth/auth-user.js';
import { CurrentUser } from '../auth/decorators/current-user.decorator.js';
import { CreateTransferDto, TransferFiltersDto, TransferQueryDto, UpdateTransferDto } from './dto/transfer.dto.js';
import { TransfersService } from './transfers.service.js';

@ApiTags('Internal Transfers')
@ApiBearerAuth()
@Controller('transfers')
export class TransfersController {
  constructor(private readonly transfers: TransfersService) {}

  /** Paginated list; search matches the reference, product name or SKU */
  @Get()
  list(@Query() query: TransferQueryDto) {
    return this.transfers.list(query);
  }

  /** Counts per status */
  @Get('summary')
  summary() {
    return this.transfers.summary();
  }

  /** CSV (one row per transfer line) for the same filters as the list */
  @Get('export')
  @ApiProduces('text/csv')
  @Header('Content-Type', 'text/csv; charset=utf-8')
  @Header('Content-Disposition', 'attachment; filename="StockSense_Transfers.csv"')
  exportCsv(@Query() filters: TransferFiltersDto) {
    return this.transfers.exportCsv(filters);
  }

  @Get(':id')
  findOne(@Param('id', ParseUUIDPipe) id: string) {
    return this.transfers.findOne(id);
  }

  /** Creates a DRAFT (reference WH/TR/000001 generated by the database). Stock isn't checked here */
  @Post()
  create(@Body() dto: CreateTransferDto, @CurrentUser() user: AuthUser) {
    return this.transfers.create(dto, user.id);
  }

  /** DRAFT / WAITING only; `items` replaces all lines */
  @Patch(':id')
  update(@Param('id', ParseUUIDPipe) id: string, @Body() dto: UpdateTransferDto, @CurrentUser() user: AuthUser) {
    return this.transfers.update(id, dto, user.id);
  }

  /** DRAFT → READY (source has the stock) or WAITING (short) */
  @Post(':id/confirm')
  @HttpCode(HttpStatus.OK)
  confirm(@Param('id', ParseUUIDPipe) id: string, @CurrentUser() user: AuthUser) {
    return this.transfers.confirm(id, user.id);
  }

  /** WAITING → READY when stock is now available */
  @Post(':id/check-availability')
  @HttpCode(HttpStatus.OK)
  checkAvailability(@Param('id', ParseUUIDPipe) id: string, @CurrentUser() user: AuthUser) {
    return this.transfers.checkAvailability(id, user.id);
  }



  /** READY → DONE: source −, destination + (409 INSUFFICIENT_STOCK if the source is short), OUT + IN ledger rows, atomically */
  @Post(':id/validate')
  @HttpCode(HttpStatus.OK)
  validate(@Param('id', ParseUUIDPipe) id: string, @CurrentUser() user: AuthUser) {
    return this.transfers.validate(id, user.id);
  }

  /** DRAFT / WAITING / READY → CANCELED (never after DONE) */
  @Post(':id/cancel')
  @HttpCode(HttpStatus.OK)
  cancel(@Param('id', ParseUUIDPipe) id: string, @CurrentUser() user: AuthUser) {
    return this.transfers.cancel(id, user.id);
  }
}
